version: '3'
services:
  gcc:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: gcc:ubuntu-22.04
    container_name: gcc
    env_file: .env
    tty: true
    working_dir: ${WORKING_DIR}
    volumes:
      - ./CMakeLists.txt:${WORKING_DIR}/CMakeLists.txt
      - ./test:${WORKING_DIR}/test
      - ./src:${WORKING_DIR}/src
      - ./include:${WORKING_DIR}/include